version: '3.1'

services:
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 80:80
    networks:
      - net1

  redis:
    image: redis:3.2
    networks:
      - net1

  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - net1
      - net2

  db:
    image: postgres:9.4
    networks:
      - net2
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  
  result:
    image: bretfisher/examplevotingapp_result
    networks:
      - net2
    ports:
      - 5001:80

networks:
  net1:
    driver: overlay
  net2:
    driver: overlay